@baseUrl = http://localhost:4004/odata/v4

### Get all employees
GET {{baseUrl}}/employee/Employees
Accept: application/json
Authorization: Basic john:

###

### Create new employee
POST {{baseUrl}}/employee/Employees
Content-Type: application/json
# Authorization: Basic luna:

{
  "firstName": "Peter",
  "lastName": "Tran",
  "email": "thaho@example.com",
  "hireDate": "2020-03-01",
  "companyCode": "DE03",
  "department_ID": "d1c8e4c9-6ad6-4e33-a65f-0f9338f346a1"
}

###

### Update employee's last name
PATCH {{baseUrl}}/employee/Employees('john.doe@example.com')
Content-Type: application/json
# Authorization: Basic luna:

{
  "lastName": "hahahah"
}

###

### Delete employee
DELETE {{baseUrl}}/employee/Employees('e5555555-e555-4555-8555-e55555555555')
Authorization: Basic john:

##############################################

### Get all Department
GET {{baseUrl}}/employee/Departments
Accept: application/json
Authorization: Basic selina:

##############################################

### Get all Roles
GET {{baseUrl}}/employee/Roles
Accept: application/json
Authorization: Basic john:
